### ISSUE TITLE
直播录制下载之后，进行合并时报错

### ISSUE THREAD

**Issue by Narip2** [yliu7949/KouShare-dl#20]
直播录制之后进行下载(不知道是不是因为只下载了部分的原因，没有等完全下载完毕就`ctrl+c`终止了程序，感觉这一点是有必要的，因为有的会议是连着的，但是只想录制某个报告人的视频)，最后合并的时候报错如下:
```
开始合并视频文件...
panic: runtime error: slice bounds out of range [-1:]

goroutine 1 [running]:
github.com/yliu7949/KouShare-dl/live.MergeTsFiles.func1({0x0?, 0xc0003c9740?}, {0x12a0d38, 0xc0003a1340}, {0xc0000695c8?, 0xf8751a?})
        github.com/yliu7949/KouShare-dl/live/live.go:309 +0x229
path/filepath.walk({0xc0003c9740, 0x2c}, {0x12a0d38, 0xc0003a1340}, 0xc000069bd0)
        path/filepath/path.go:433 +0x123
path/filepath.walk({0xc0003c8030, 0x29}, {0x12a0d38, 0xc00041e070}, 0xc000069bd0)
        path/filepath/path.go:457 +0x285
path/filepath.walk({0xc00034c600, 0x20}, {0x12a0d38, 0xc0003a1a40}, 0xc000069bd0)
        path/filepath/path.go:457 +0x285
path/filepath.walk({0xc00034d1a0, 0x1b}, {0x12a0d38, 0xc0003c1b20}, 0xc000069bd0)
        path/filepath/path.go:457 +0x285
path/filepath.walk({0xc00000f5c0, 0xd}, {0x12a0d38, 0xc00015f110}, 0xc000069bd0)
        path/filepath/path.go:457 +0x285
path/filepath.walk({0xc00000f1c0, 0x9}, {0x12a0d38, 0xc00015e1c0}, 0xc000069bd0)
        path/filepath/path.go:457 +0x285
path/filepath.walk({0x11edb0b, 0x2}, {0x12a0d38, 0xc00015e000}, 0xc000069bd0)
        path/filepath/path.go:457 +0x285
path/filepath.Walk({0x11edb0b, 0x2}, 0xc000107bd0)
        path/filepath/path.go:520 +0x6c
github.com/yliu7949/KouShare-dl/live.MergeTsFiles({0x11edb0b, 0x2}, {0xc00000e0d8, 0x8})
        github.com/yliu7949/KouShare-dl/live/live.go:305 +0x132
github.com/yliu7949/KouShare-dl/cmd/ks.MergeCmd.func1(0xc00014cc00?, {0xc0000509a0?, 0x2?, 0x2?})
        github.com/yliu7949/KouShare-dl/cmd/ks/commands.go:121 +0x116
github.com/spf13/cobra.(*Command).execute(0xc00014cc00, {0xc000050980, 0x2, 0x2})
        github.com/spf13/cobra@v1.6.0/command.go:920 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0xc00014c000)
        github.com/spf13/cobra@v1.6.0/command.go:1040 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.6.0/command.go:968
main.main()
        ./ks.go:34 +0x31a
```

**Comment by yliu7949** [comment]
未能复现该问题，正常情况下即使使用 `Ctrl+C` 中断直播间录制也是不会发生错误的。如果能进一步提供你执行的具体命令将会很有帮助。另外使用 `-a` 标志可在下载时将视频片段自动合并为一个 `.ts` 文件，例如 `ks record RoomID -a`。

**Comment by Narip2** [comment]
明白了，当前文件夹下面还有除了.ts视频片段之外的别的文件，所以合并的时候报错了，需要把.ts文件单独放到一个文件夹里面进行合并。
