### ISSUE TITLE
反馈一个运行时的报错

### ISSUE THREAD

**Issue by JHees** [yliu7949/KouShare-dl#24]
在录制直播时出现的报错，随后程序停止了运行，报错信息如下
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x40 pc=0x55c168]

goroutine 1 [running]:
github.com/yliu7949/KouShare-dl/user.MyGetRequest({0xc00023e6c7?, 0xc000025098?}, {0x0, 0x0, 0x0?})
        github.com/yliu7949/KouShare-dl/user/user.go:177 +0x5c8
github.com/yliu7949/KouShare-dl/live.(*Live).getNewTsURLBym3u8(0xc0000fa0f0)
        github.com/yliu7949/KouShare-dl/live/live.go:207 +0x3a
github.com/yliu7949/KouShare-dl/live.(*Live).recordLive(0xc0000fa0f0, 0x0)
        github.com/yliu7949/KouShare-dl/live/live.go:188 +0x45
github.com/yliu7949/KouShare-dl/live.(*Live).WaitAndRecordTheLive(0xc0000fa0f0, {0x0?, 0x0?}, 0xb3?)
        github.com/yliu7949/KouShare-dl/live/live.go:96 +0x78b
github.com/yliu7949/KouShare-dl/cmd/ks.RecordCmd.func1(0xc0000f8900?, {0xc000072f70?, 0x1?, 0x1?})
        github.com/yliu7949/KouShare-dl/cmd/ks/commands.go:89 +0x137
github.com/spf13/cobra.(*Command).execute(0xc0000f8900, {0xc000072f40, 0x1, 0x1})
        github.com/spf13/cobra@v1.6.0/command.go:920 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0xc0000f8000)
        github.com/spf13/cobra@v1.6.0/command.go:1040 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.6.0/command.go:968
main.main()
        ./ks.go:34 +0x31a
```
随后再次执行`ks record`命令，报错误如下
```
登陆凭证有效。

Error: unknown command "PathtoKS\\ks.exe" for "ks"
Run 'ks --help' for usage.
```
第三次执行`record`命令后成功重新开始录制。

**Comment by yliu7949** [comment]
反馈的问题已收到，如果在后续测试中能成功复现该问题，我将会对其进行修复。
